GET http://localhost:3000/

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Davit"
}

###

get http://localhost:3000/H0JKUi

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "davita",
    "password": "password"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGY1Y2QwOTA4NjAwOTQyYThmYzMxNDEiLCJpYXQiOjE2MjY3MjE1NDV9.kIniYrvitmNGBrOwWkA283QKaRdQDqzxVOzWTIv7KDI

{
    "name": "davit",
    "password": "password"
}

###
POST http://localhost:3000/url/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGY1Y2QwOTA4NjAwOTQyYThmYzMxNDEiLCJpc0F1dGhlbnRpY2F0ZWQiOnRydWUsImlhdCI6MTYyNjczMzQ1NX0.gRmZBINY5eVufX82zb-08RkGdXhKbwoxGJcXsZA046Q

{
    "url": "dzalian.grdzelie/misamarti"
}